# Uncomment the next line to define a global platform for your project

target 'Royal Cafe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Royal Cafe

  pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
end
